# Generated by Django 4.2 on 2023-04-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HDCPGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1)),
                ('lower', models.SmallIntegerField(default=0)),
                ('upper', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
